# Generated by Django 3.1 on 2022-02-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220208_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='images',
            new_name='image',
        ),
    ]
